export enum AssetCategory {
  Background = 'background',
  Foreground = 'foreground',
  Character = 'character',
  Product = 'product',
  Particle = 'particle',
  Icon = 'icon',
  Texture = 'texture',
  Overlay = 'overlay',
  Lighting = 'lighting',
  Audio = 'audio',
  Video = 'video'
}

export enum SceneId {
  Global = 'Global',
  Scene1_Arrival = 'Scene1_Arrival',
  Scene2_Forest = 'Scene2_Forest',
  Scene3_Discovery = 'Scene3_Discovery',
  Scene4_Harvest = 'Scene4_Harvest',
  Scene4_5_Honey = 'Scene4_5_Honey',
  Scene5_Collection = 'Scene5_Collection',
  Products = 'Products'
}

export interface AssetDefinition {
  id: string;
  scene: SceneId;
  category: AssetCategory;
  type: 'image' | 'video' | 'audio' | 'texture';
  source: string; // Original raw file
  optimizedSources?: { avif?: string; webp?: string };
  fallback?: string;
  width?: number;
  height?: number;
  aspectRatio?: number;
  preloadStage: number;
  priority: 'critical' | 'high' | 'normal' | 'low' | 'deferred';
  loadingStrategy: 'eager' | 'lazy' | 'viewport';
  altText?: string;
  description?: string;
  licenseSource?: string;
  version?: string;
  hash?: string;
  owner?: string;
  lastOptimizedTimestamp?: number;
  status: 'active' | 'deprecated';
}

export const Assets: Record<string, AssetDefinition> = {
  heroBg: {
    id: 'hero-bg',
    scene: SceneId.Scene1_Arrival,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/hero_bg.png',
    optimizedSources: {
      avif: '/images/optimized/hero_bg.avif',
      webp: '/images/optimized/hero_bg.webp'
    },
    preloadStage: 1,
    priority: 'critical',
    loadingStrategy: 'eager',
    altText: 'A beautiful cinematic view of the Wayanad forest',
    status: 'active',
  },
  forestPath: {
    id: 'forest-path',
    scene: SceneId.Scene1_Arrival,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/forest-path.jpg',
    optimizedSources: { avif: '/images/optimized/forest-path.avif', webp: '/images/optimized/forest-path.webp' },
    preloadStage: 1,
    priority: 'critical',
    loadingStrategy: 'eager',
    altText: 'A path leading deep into the spice forests',
    status: 'active',
  },
  forestMistBg: {
    id: 'forest-mist-bg',
    scene: SceneId.Scene2_Forest,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/forest_mist_background.jpg',
    optimizedSources: { avif: '/images/optimized/forest_mist_background.avif', webp: '/images/optimized/forest_mist_background.webp' },
    preloadStage: 1,
    priority: 'critical',
    loadingStrategy: 'eager',
    altText: 'Mist hovering over the dense forest floor',
    status: 'active',
  },
  forestCanopy: {
    id: 'forest-canopy',
    scene: SceneId.Scene2_Forest,
    category: AssetCategory.Foreground,
    type: 'image',
    source: '/images/forest_canopy.png',
    preloadStage: 1,
    priority: 'critical',
    loadingStrategy: 'eager',
    status: 'active',
  },
  midGroundVegetation: {
    id: 'mid-ground-vegetation',
    scene: SceneId.Scene2_Forest,
    category: AssetCategory.Foreground,
    type: 'image',
    source: '/images/mid_ground_vegetation.png',
    preloadStage: 2,
    priority: 'high',
    loadingStrategy: 'viewport',
    status: 'active',
  },
  foregroundFoliage: {
    id: 'foreground-foliage',
    scene: SceneId.Scene2_Forest,
    category: AssetCategory.Foreground,
    type: 'image',
    source: '/images/foreground_foliage.png',
    preloadStage: 2,
    priority: 'high',
    loadingStrategy: 'viewport',
    status: 'active',
  },
  forestLayerMountains: {
    id: 'forest-layer-mountains',
    scene: SceneId.Scene1_Arrival,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/forest_layer_mountains.png',
    preloadStage: 1,
    priority: 'critical',
    loadingStrategy: 'eager',
    status: 'active',
  },
  honeyBg: {
    id: 'honey-bg',
    scene: SceneId.Scene4_5_Honey,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/honey_bg.png',
    preloadStage: 4,
    priority: 'normal',
    loadingStrategy: 'lazy',
    status: 'active',
  },
  sunsetBg: {
    id: 'sunset-bg',
    scene: SceneId.Scene5_Collection,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/sunset.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    status: 'active',
  },
  noiseTexture: {
    id: 'noise-texture',
    scene: SceneId.Global,
    category: AssetCategory.Texture,
    type: 'image',
    source: '/images/noise.png',
    preloadStage: 1,
    priority: 'high',
    loadingStrategy: 'eager',
    status: 'active',
  },
  blackPepper: {
    id: 'black-pepper',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/black_pepper.jpg',
    preloadStage: 3,
    priority: 'normal',
    loadingStrategy: 'lazy',
    altText: 'Sun-dried black pepper corns',
    status: 'active',
  },
  whitePepper: {
    id: 'white-pepper',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/white_pepper.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Mild earthy white pepper',
    status: 'active',
  },
  greenPepper: {
    id: 'green-pepper',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/green_pepper.jpg',
    preloadStage: 3,
    priority: 'normal',
    loadingStrategy: 'lazy',
    altText: 'Fresh vibrant green pepper',
    status: 'active',
  },
  pepperPowder: {
    id: 'pepper-powder',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/pepper_powder.jpg',
    preloadStage: 3,
    priority: 'normal',
    loadingStrategy: 'lazy',
    altText: 'Finely milled pepper powder',
    status: 'active',
  },
  forestHoney: {
    id: 'forest-honey',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/forest_honey.jpg',
    preloadStage: 4,
    priority: 'normal',
    loadingStrategy: 'lazy',
    altText: 'Wild-harvested golden forest honey',
    status: 'active',
  },
  cardamom: {
    id: 'cardamom',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/cardamom.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Sweet floral cardamom pods',
    status: 'active',
  },
  cinnamon: {
    id: 'cinnamon',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/cinnamon.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Woody cinnamon quills',
    status: 'active',
  },
  clove: {
    id: 'clove',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/clove.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Aromatic clove buds',
    status: 'active',
  },
  nutmeg: {
    id: 'nutmeg',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/nutmeg.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Nutty warm nutmeg',
    status: 'active',
  },
  turmeric: {
    id: 'turmeric',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/turmeric.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Golden earthy turmeric roots',
    status: 'active',
  },
  redChilli: {
    id: 'red-chilli',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/chili.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Sun-dried vibrant red chillies',
    status: 'active',
  },
  mace: {
    id: 'mace',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/cinnamon-nutmeg.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Crimson mace aril blades',
    status: 'active',
  },
  ginger: {
    id: 'ginger',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/ginger.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Fresh organic ginger rhizomes',
    status: 'active',
  },
  coriander: {
    id: 'coriander',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/coriander.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Golden dried coriander seeds',
    status: 'active',
  },
  cumin: {
    id: 'cumin',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/white_pepper.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Aromatic earthy cumin seeds',
    status: 'active',
  },
  spiceBlends: {
    id: 'crushed-pepper',
    scene: SceneId.Products,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/crushed_pepper.jpg',
    preloadStage: 5,
    priority: 'low',
    loadingStrategy: 'lazy',
    altText: 'Coarsely cracked whole black pepper',
    status: 'active',
  },
  processing: {
    id: 'processing',
    scene: SceneId.Scene4_Harvest,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/processing.jpg',
    preloadStage: 4,
    priority: 'normal',
    loadingStrategy: 'viewport',
    status: 'active',
  },
  pepperRaw: {
    id: 'pepper-raw',
    scene: SceneId.Scene3_Discovery,
    category: AssetCategory.Product,
    type: 'image',
    source: '/images/pepper.jpg',
    preloadStage: 3,
    priority: 'high',
    loadingStrategy: 'viewport',
    status: 'active',
  },
  farmerHands: {
    id: 'farmer-hands',
    scene: SceneId.Scene3_Discovery,
    category: AssetCategory.Background,
    type: 'image',
    source: '/images/farmer-hands.jpg',
    preloadStage: 3,
    priority: 'high',
    loadingStrategy: 'viewport',
    status: 'active',
  }
};
